### PR TITLE
Use @RestController, fixes #50

### LINKED ISSUE #50: Tutorial references @Controller while (I think) it should reference @RestController
Under section [Writing your first Kotlin controller] of the tutorial, the example code uses the `@Controller` annotation, but apparently this is an older annotation, and instead `@RestController` should be used. With the former, the application just gives a 404 instead of show the expected hello world.

[Writing your first Kotlin controller]: https://spring.io/guides/tutorials/spring-boot-kotlin/#_writing_your_first_kotlin_controller

### PR DESCRIPTION
**Pull request by Alveel**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Alveel Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-boot-kotlin&pullRequestId=51)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-spring-boot-kotlin&pullRequestId=51) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Alveel Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-boot-kotlin&pullRequestId=51)!

**Comment by OlegDokuka** [comment]
hey @Alveel!

What is the purpose of that changes?

**Comment by Alveel** [comment]
@OlegDokuka the `Controller` annotation will no longer achieve the desired results in recent Spring versions, so when following the tutorial people will get stuck at this step. The `RestController` is I believe the new controller to use instead. I haven't been able to find the changelog entry or release notes where this got announced, however.

Also see #50.

**Comment by OlegDokuka** [comment]
@Alveel it is not. `@Controller` and `@RestController` have different purposes. `@RestController` is designed to automatically add `@RespondeBody` to all the methods within the annotated controller, which means that if you do `return "abcd";` the result will be returning a pojo. In contrast, when the controller is annotated with `@Controller` annotation, all the responses are assumed to return `View` which delivers HTML content or a template name that the controller has to render before sending the output. It said, both controllers are `new` but they serve different functions and in the case of HtmlController we need to render a template instead of returning a POJO

**Pull request closed without merging**
