### PR TITLE
Split mocked tests

### PR DESCRIPTION
**Pull request by joshrotenberg**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@joshrotenberg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-boot-kotlin&pullRequestId=40)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/tut-spring-boot-kotlin&pullRequestId=40) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@joshrotenberg Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/tut-spring-boot-kotlin&pullRequestId=40)!

**Comment by sdeleuze** [comment]
Could you please update the guide accordingly as well?

**Comment by joshrotenberg** [comment]
I can't remember why I thought this was worth a PR but I don't think it is anymore so closing.

**Pull request closed without merging**
